### ISSUE TITLE
fleet_state_visualizer error

### ISSUE THREAD

**Issue by Sunshengjin** [osrf/rmf_core#320]
**Workspace information:**
 - Operating system and version:
 - ROS distribution: ROS2 foxy
 - ROS installation method: **Binary**
 - RMF installation method: **Source**
 - RMF source versions :
   - `rmf_demos` branch or commit hash: release-21.01 
   - `rmf_core` branch or commit hash:  release-21.01
   - `rmf_schedule_visualizaer` branch or commit hash:   release-21.01

**Steps to Reproduce**
1. ros2 launch demos office.launch.xml

**Describe the bug**
When I run rmf_demos , the fleet_state_visualizer package starts an error, which causes the robot not to be displayed in RVIZ. 
terminal output:
```
[fleet_state_visualizer-5] [INFO] [1617097977.982786019] [fleet_state_visualizer]: hello i am fleet state visualizer
[gzclient-11] Gazebo multi-robot simulator, version 11.3.0
[gzclient-11] Copyright (C) 2012 Open Source Robotics Foundation.
[gzclient-11] Released under the Apache 2 License.
[gzclient-11] http://gazebosim.org
[gzclient-11] 
[fleet_state_visualizer-5] Traceback (most recent call last):
[fleet_state_visualizer-5]   File "/opt/ros/foxy/lib/python3.8/site-packages/rosidl_generator_py/import_type_support_impl.py", line 46, in import_type_support
[fleet_state_visualizer-5]     return importlib.import_module(module_name, package=pkg_name)
[fleet_state_visualizer-5]   File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
[fleet_state_visualizer-5]     return _bootstrap._gcd_import(name[level:], package, level)
[fleet_state_visualizer-5]   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
[fleet_state_visualizer-5]   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
[fleet_state_visualizer-5]   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
[fleet_state_visualizer-5]   File "<frozen importlib._bootstrap>", line 657, in _load_unlocked
[fleet_state_visualizer-5]   File "<frozen importlib._bootstrap>", line 556, in module_from_spec
[fleet_state_visualizer-5]   File "<frozen importlib._bootstrap_external>", line 1101, in create_module
[fleet_state_visualizer-5]   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
[fleet_state_visualizer-5] ImportError: /home/sunshengjin/rmf_demos_ws/install/rmf_fleet_msgs/lib/python3.8/site-packages/rmf_fleet_msgs/rmf_fleet_msgs_s__rosidl_typesupport_c.cpython-38-x86_64-linux-gnu.so: undefined symbol: rmf_fleet_msgs__msg__dock__convert_from_py
[fleet_state_visualizer-5] 
[fleet_state_visualizer-5] During handling of the above exception, another exception occurred:
[fleet_state_visualizer-5] 
[fleet_state_visualizer-5] Traceback (most recent call last):
[fleet_state_visualizer-5]   File "/home/sunshengjin/rmf_demos_ws/install/fleet_state_visualizer/lib/fleet_state_visualizer/fleet_state_visualizer", line 11, in <module>
[fleet_state_visualizer-5]     load_entry_point('fleet-state-visualizer==0.0.0', 'console_scripts', 'fleet_state_visualizer')()
[fleet_state_visualizer-5]   File "/home/sunshengjin/rmf_demos_ws/install/fleet_state_visualizer/lib/python3.8/site-packages/fleet_state_visualizer/fleet_state_visualizer.py", line 183, in main
[fleet_state_visualizer-5]     n = FleetStateVisualizer(args.map_name)
[fleet_state_visualizer-5]   File "/home/sunshengjin/rmf_demos_ws/install/fleet_state_visualizer/lib/python3.8/site-packages/fleet_state_visualizer/fleet_state_visualizer.py", line 25, in __init__
[fleet_state_visualizer-5]     self.create_subscription(
[fleet_state_visualizer-5]   File "/opt/ros/foxy/lib/python3.8/site-packages/rclpy/node.py", line 1201, in create_subscription
[fleet_state_visualizer-5]     check_for_type_support(msg_type)
[fleet_state_visualizer-5]   File "/opt/ros/foxy/lib/python3.8/site-packages/rclpy/type_support.py", line 29, in check_for_type_support
[fleet_state_visualizer-5]     msg_type.__class__.__import_type_support__()
[fleet_state_visualizer-5]   File "/home/sunshengjin/rmf_demos_ws/install/rmf_fleet_msgs/lib/python3.8/site-packages/rmf_fleet_msgs/msg/_fleet_state.py", line 27, in __import_type_support__
[fleet_state_visualizer-5]     module = import_type_support('rmf_fleet_msgs')
[fleet_state_visualizer-5]   File "/opt/ros/foxy/lib/python3.8/site-packages/rosidl_generator_py/import_type_support_impl.py", line 48, in import_type_support
[fleet_state_visualizer-5]     raise UnsupportedTypeSupport(pkg_name)
[fleet_state_visualizer-5] rosidl_generator_py.import_type_support_impl.UnsupportedTypeSupport: Could not import 'rosidl_typesupport_c' for package 'rmf_fleet_msgs'
[building_systems_visualizer-6] [INFO] [1617097978.129750992] [building_systems_visualizer]: Building systems visualizer started...
[building_map_server-3] [INFO] [1617097978.159663936] [building_map_server]: loading map path: /home/sunshengjin/rmf_demos_ws/install/rmf_demo_maps/share/rmf_demo_maps/office/office.building.yaml
[ERROR] [fleet_state_visualizer-5]: process has died [pid 58163, exit code 1, cmd '/home/sunshengjin/rmf_demos_ws/install/fleet_state_visualizer/lib/fleet_state_visualizer/fleet_state_visualizer -m L1 --ros-args --params-file /tmp/launch_params_hgxn1tt7'].

```
According to the terminal output, I think this may be a problem with rmf_fleet_msgs.

**Comment by Sunshengjin** [comment]
I found that this was a compilation problem. When I deleted the build and install folders and recompiled the entire project, the problem was solved. Sorry to bother
